using System;

namespace PascalTriangle
{
    class Program
    {
        static void Main(string[] args)
        {
            //generate and visualize the Pascal's Triangle
	    //first row contains 1
	    //next number is generated by sum of the two numbers on the row above it
	    
	    
        }
    }
}
